ARG TAG=latest
FROM selenium/standalone-chrome:$TAG
# https://github.com/SeleniumHQ/docker-selenium
MAINTAINER hyunil.shin <hyunil.shin@nhnent.com>

USER root

RUN  echo "deb http://ftp.daumkakao.com/ubuntu xenial main universe\n" > /etc/apt/sources.list \
  && echo "deb http://ftp.daumkakao.com/ubuntu xenial-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu xenial-security main universe\n" >> /etc/apt/sources.list


#=========================================== 
# set locale ko_KR
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
RUN apt-get update
RUN apt-get install -y language-pack-gnome-ko language-pack-gnome-en
RUN locale-gen ko_KR.UTF-8
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR.UTF-8
ENV LC_ALL ko_KR.UTF-8


#==========================================
# add Korean font
RUN apt-get install -y fontconfig
RUN mkdir -p /usr/share/fonts/nanumfont
COPY nanum_font/*.ttf /usr/share/fonts/nanumfont/
RUN fc-cache -f -v


#==========================================
# time and date
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
ENV TZ=Asia/Seoul
RUN echo "Asia/Seoul" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN date

# testcafe 실행에 필요한 도구
RUN apt-get install -y git unzip

###
USER seluser
